SELECT T0.[Number]
       ,T0.[TransId]
       ,T0.[RefDate]
       ,T0.[DueDate]
       ,T0.[TaxDate]
       ,T0.[TransCode]
       ,T0.[TransType]
       ,T0.[BaseRef]
       ,T0.[Ref1]
       ,T0.[Ref2]
       ,T0.[Ref3]
       ,T0.[Memo]
       ,T0.[U_removed]
       ,T0.[BtfStatus]
       ,T0.[AutoStorno]
       ,T0.[Project]
       ,T2.[PrjName]
       ,T1.[Line_ID] + 1
       ,T3.[Segment_0]
       ,T3.[AcctName]
       ,T4.[CardName]
       ,T1.[Debit]
       ,T1.[Credit]
       ,T1.[LineMemo]
       ,T1.[ProfitCode]
       ,T5.[OcrName]
  FROM [dbo].[OJDT] T0
       INNER JOIN [dbo].[JDT1] T1 ON T0.[TransId] = T1.[TransId]
       LEFT OUTER JOIN OPRJ T2 ON T0.[Project]    = T2.[PrjCode]
       LEFT OUTER JOIN OACT T3 ON T1.[Account]    = T3.[AcctCode]
       LEFT OUTER JOIN OCRD T4 ON T1.[shortname]  = T4.[CardCode]
       LEFT OUTER JOIN OOCR T5 ON T1.[ProfitCode] = T5.[OcrCode];
GO

